kind: Pod
apiVersion: v1
metadata:
  labels: 
    app: kube-system
  name: kube-controller-manager
spec:
  hostNetwork: true
  containers: 
  - command:
    - /usr/local/bin/hyperkube
    - controller-manager
    - --kubeconfig=/etc/kubernetes/config
    - --root-ca-file=/etc/kubernetes/ca/ca.crt
    - --service-account-private-key-file=/etc/kubernetes/service-account/private.key
    - --logtostderr=true
    name: kube-controller-manager
    image: docker.nihaomai.com/cqthink/docker/hyperkube:1.9.3
    volumeMounts:
    - name: kubeconfig
      mountPath: /etc/kubernetes
      readOnly: true
    livenessProbe:
      httpGet:
        scheme: HTTP
        host: 127.0.0.1
        port: 10252
        path: /healthz
      initialDelaySeconds: 15
      timeoutSeconds: 15
  volumes:
  - name: kubeconfig
    hostPath:
      path: /etc/kubernetes
