kind: Pod
apiVersion: v1
metadata:
  labels: 
    app: kube-system
  name: kube-controller-manager
spec:
  hostNetwork: true
  containers: 
  - args:
    - controller-manager
    - --kubeconfig=/etc/kubernetes/config
    - --root-ca-file=/etc/kubernetes/ca/ca.crt
    - --service-account-private-key-file=/etc/kubernetes/service-account/private.key
    # - --allocate-node-cidrs=true
    # - --cluster-cidr=162.8.0.0/16
    # - --service-cluster-ip-range=162.9.0.0/16
    - --logtostderr=true
    name: kube-controller-manager
    image: docker.nihaomai.com/cqthink/docker/hyperkube:1.12.1
    volumeMounts:
    - name: kubeconfig
      mountPath: /etc/kubernetes
      readOnly: true
    livenessProbe:
      httpGet:
        scheme: HTTP
        host: 127.0.0.1
        port: 10252
        path: /healthz
      initialDelaySeconds: 15
      timeoutSeconds: 15
  volumes:
  - name: kubeconfig
    hostPath:
      path: /etc/kubernetes
