kind: Pod
apiVersion: v1
metadata:
  labels: 
    app: kube-system
  name: kube-scheduler
spec:
  hostNetwork: true
  containers: 
  - command:
    - /usr/local/bin/hyperkube
    - scheduler
    - --kubeconfig=/etc/kubernetes/config
    name: kube-scheduler
    image: docker.nihaomai.com/cqthink/docker/hyperkube:1.9.3
    volumeMounts:
    - name: kubeconfig
      mountPath: /etc/kubernetes
      readOnly: true
    livenessProbe:
      httpGet:
        scheme: HTTP
        host: 127.0.0.1
        port: 10251
        path: /healthz
      initialDelaySeconds: 15
      timeoutSeconds: 15
  volumes:
  - name: kubeconfig
    hostPath:
      path: /etc/kubernetes
