apiVersion: v1
kind: Secret
metadata:
  name: cephfs-secret
  namespace: kube-system
data:
  key: QVFERjg3RmJaT3FoT2hBQTZ5OVhsZEJZMlZsNS9JWGhsdHNQT2c9PQ==

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: cephfs
  namespace: kube-system
  labels:
    type: cephfs
spec:
  capacity:
    storage: 500Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
    - ReadOnlyMany
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  cephfs:
    monitors:
    - 192.168.0.2:6789
    - 192.168.0.241:6789
    - 192.168.0.191:6789
    path: "/PIKS8"
    secretRef: 
      name: cephfs-secret
      namespace: kube-system
